theme: jekyll-theme-slate
title: Afstudeer blog - Merik Westerveld - Info Support
description: Deze blog fungeert als inzage document van mijn afstudeerproces tijdens mijn afstudeerstage bij Info Support. 
